#networks:
#  tailscale:
#    driver: bridge

services:
#  tailscale:
#  image: tailscale/tailscale:latest
#  container_name: tailscale
#  restart: unless-stopped
#  network_mode: host
#  volumes:
#   - ./tailscale/state:/var/lib/tailscale
#   - /dev/net/tun:/dev/net/tun
#  cap_add:
#   - NET_ADMIN
#   - SYS_MODULE
#  environment:
#   TS_AUTHKEY: ${TS_AUTHKEY} 
#   TS_EXTRA_ARGS: --advertise-tags=tag:container

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    network_mode: host
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/data:/data
      - ./caddy/config:/config

  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./jellyfin/config:/config
      - ./jellyfin/cache:/cache
      - media:/srv/media
    environment:
      TZ: America/New_York

volumes:
  media:
