theme:
  light: false 
  background-color: 0 0 0
  primary-color: 360 100 100
  contrast-multiplier: 1.3

branding:
  hide-footer: true
  # logo-text: reger.cloud

pages:
  - name: reger.cloud
    hide-desktop-navigation: true
    columns:
      - size: small
        widgets:
          - type: weather
            units: metric
            hour-format: 24h
            location: Columbus, Ohio, United States

          - type: clock
            hour-format: 24h
            timezones:
              - timezone: Etc/UTC
                label: UTC
              - timezone: Europe/Stockholm
                label: Stockholm
              - timezone: Asia/Tokyo
                label: Tokyo
          
          - type: calendar
            first-day-of-week: monday

      - size: full
        widgets:          
          - type: search
            search-engine: https://kagi.com/search?q={QUERY}
          
          - type: bookmarks
            groups:
              - links:
                  - title: Mail
                    url: https://mail.reger.cloud
                  - title: Music
                    url: https://music.reger.cloud
                  - title: Photos
                    url: https://photos.reger.cloud

          - type: rss
            limit: 20
            cache: 12h
            feeds:
              - url: https://drewdevault.com/blog/index.xml
              - url: https://sourcehut.org/blog/index.xml
              - url: https://go.dev/blog/feed.atom
        
          - type: videos
            style: grid-cards
            collapse-after-rows: 2
            channels:
              - UCQuL1wpN5RHCSgd38-DsE3w # Blank First Page
              - UCuVLG9pThvBABcYCm7pkNkA # Climate Town
              - UCTSRIY3GLFYIpkR2QwyeklA # Drew Gooden
              - UC8iPVSFr42KUFf8DKsmnvSw # GIFGAS
              - UCgBVkKoOAr3ajSdFFLp13_A # Krazam
              - UCtHaxi4GTYDpJgMSGy7AeSw # Michael Reeves
              - UCUMwY9iS8oMyWDYIe6_RmoA # No Boilerplate
              - UCuTQDPUE12sy7g1xf1LAdTA # Noel Miller
              - UCLF2lvHVw5quuoigI3rcQkQ # ultraromance
              - UC6nSFpj9HTCZ5t-N3Rm3-HA # Vsauce
              - UCfMJ2MchTSW2kWaT0kK94Yw # William Osman
              - UCbguawtJlHjxXzdAskubQVg # William Osman 2
              - UCLGSpxD0XXHnbXtDJJqMqDw # yukikawae

          - type: hacker-news
            limit: 15
            collapse-after: 5

          - type: group
            widgets:
              - type: reddit
                subreddit: framework
                show-thumbnails: true
              - type: reddit
                subreddit: lightphone
                show-thumbnails: true
              - type: reddit
                subreddit: bluejackets
                show-thumbnails: true
        
      - size: small
        widgets:
          - type: docker-containers
            hide-by-default: false
            
          - type: monitor
            cache: 15m
            title: Services
            sites:
              - title: Jellyfin
                url: https://music.reger.cloud
              - title: Immich
                url: https://photos.reger.cloud
              - title: Alps Webmail
                url: https://mail.reger.cloud

          - type: releases
            cache: 1d
            repositories:
              - glanceapp/glance
              - immich-app/immich
              - jellyfin/jellyfin
              - caddyserver/caddy