services:
  glance:
    container_name: glance
    image: glanceapp/glance
    restart: unless-stopped
    volumes:
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
    labels:
      glance.name: Glance
      glance.url: https://reger.cloud
      glance.id: glance
